### ISSUE TITLE
embedding HTML

### ISSUE THREAD

**Issue by kingsleyh** [repeatedly/mustache-d#25]
Hi

How can I em bed HTML? I realise this is not exactly the correct usage of a template system - but I have some dynamic html I want to get into the finished rendered page.

         context["html"] = "<b>Hello</b>";

That renders \<b>Hello\</b> rather than making the text bold.

Any help greatly appreciated.

**Comment by kingsleyh** [comment]
I've found a workaround to make it work:

        context["page_html"] = (string str) { return page.html(); };
        {{#page_html}}replaced{{/page_html}}

**Comment by repeatedly** [comment]
How about use `{{{html}}}` instead of `{{name}}`?

**Comment by kingsleyh** [comment]
ah using triple braces worked - I didn't know about that - thanks :)
