### ISSUE TITLE
use of @safe causing problems

### ISSUE THREAD

**Issue by kmq** [repeatedly/mustache-d#27]
When using mustache-d (master as of today)  in a vibe.d project under dub in dmd v2.72.0 I receive a bunch of errors, that are probably related to v2.72.0 being more strict.

    ../../../external_projects/mustache-d/src/mustache.d(191,21): Error: field Section.list cannot access pointers in @safe code that overlap other fields
    ../../../external_projects/mustache-d/src/mustache.d(1309,17): Error: field Node.text cannot access pointers in @safe code that overlap other fields
    ../../../external_projects/mustache-d/src/mustache.d(1323,17): Error: field Node.key cannot access pointers in @safe code that overlap other fields
    ../../../external_projects/mustache-d/src/mustache.d(612,15): Error: template instance mustache.MustacheEngine!string.MustacheEngine.render!(Appender!string) error instantiating
    source/app.d(95,40):        instantiated from here: render!()
    source/app.d(1134,37): Error: template instance app.ModelService!(Foo) error instantiating
    ../../../external_projects/mustache-d/src/mustache.d(179,21): Error: field Section.var cannot access pointers in @safe code that overlap other fields
    ../../../external_projects/mustache-d/src/mustache.d(185,21): Error: field Section.func cannot access pointers in @safe code that overlap other fields
    ../../../external_projects/mustache-d/src/mustache.d(197,21): Error: field Section.list cannot access pointers in @safe code that overlap other fields
    source/view.d(14,7): Error: template instance mustache.MustacheEngine!string error instantiating

**Comment by repeatedly** [comment]
Thanks for pointing this out.
I will check this issue later.
